import type { Difficulty } from "./types";

// Real tasks from the Odysseys benchmark (data/odysseys.json) — shown to
// annotators as the quality bar for each difficulty. Text verbatim.
export type BenchmarkExample = { level: Difficulty; title: string; text: string };

export const BENCHMARK_EXAMPLES: BenchmarkExample[] = [
  {
    level: "low",
    title: "Scout the new seasonal drinks buzz",
    text: "I’m curious whether any new seasonal drinks are actually landing well right now, so could you open Reddit and check the newest posts in r/starbucks for anything about recent or seasonal drink releases, then read into the comments enough to tell me whether people seem excited, disappointed, or mixed on them. After that, stay on Reddit and do the same thing in r/DunkinDonuts so I can compare whether Dunkin’s newly discussed drinks are getting a warmer or colder reaction than Starbucks at the moment. If one drink post clearly looks the most loved, most upvoted, or just the most viral between the two subreddits, open that specific post in a separate tab and leave it there so I can look at it myself. Then, as a totally separate palate cleanser, go to Bored Panda and open their collection of cute and funny angry cat photos shared by owners, and tell me the exact page title while leaving that page open too so I can glance through the pictures later.",
  },
  {
    level: "low",
    title: "A pop-culture roundup for a friend",
    text: "I want to send a friend a quick little roundup that mixes pop-culture, memes, and actual news, so could you start on Reddit and find a discussion thread about Coraline, open the actual thread page, and grab the exact thread title for me because I want the wording to be precise. While you’re still on Reddit, go over to r/starterpacks and pick two recent meme-style posts that feel funny enough to sit next to the Coraline item, and open each of those posts in its own tab so I can compare them later and make sure they’re really the kind of starterpack jokes I’d send to someone. Then switch to CNN and find the latest breaking news story about Iran, open the article itself, and note the exact headline plus the publication time so I can include one current-events item that’s clearly sourced. In the end, give me a short, friend-ready update that includes the Coraline thread title, the two r/starterpacks post titles, the CNN Iran headline with its publication time, and a natural sounding summary of these.",
  },
  {
    level: "medium",
    title: "Pull datasets from a Stanford lecture",
    text: "Help me open the Stanford CS231N introduction lecture on YouTube and start playing it. Create a list of 3 of the datasets they mention in the lecture (with relevant timestamps for each), and then help me find a way to download these 3 datasets. Go to the source and pull up the tab with the download link for all three datasets. Keep all relevant dataset links open in multiple tabs and provide a summary of them.",
  },
  {
    level: "medium",
    title: "Narrow down a London \u2192 Seoul trip",
    text: "I'm planning a trip from London to Seoul around July and want you to help me narrow things down in a realistic booking flow. First, compare the cheapest round-trip economy flight options you can find from London to Seoul for a departure on July 17th and return in early August using the flight sites available, and use what you find to identify the best-value option overall. Once you've got that flight shortlist and winner, switch to Booking.com and check two Seoul properties I might use for my whole stay — The Joseon Hotel and The Lotte Hotel. For each one, look at the guest review score and read recent reviews so I can tell whether either place seems reliably good enough for a pre-flight night. In the end, give me a concise recommendation that names the cheapest flight source and fare you found, summarizes whether The Joseon Hotel and The Lotte Hotel are generally very positive, and highlights at least three recent review takeaways for The Lotte Hotel so I can decide if I should book that hotel before the London flight.",
  },
  {
    level: "high",
    title: "A full Palm Springs wedding trip plan",
    text: "I'm flying from Pittsburgh to a wedding in Palm Springs on the 3rd of next month and I need help putting together a full trip plan in the browser so I can actually see everything. Please start on Google Flights and search for round-trip flights from Pittsburgh to LAX, picking dates so I land at least 2 days before the wedding and get back to Pittsburgh by the 5th, and prioritize non-stop options if they exist — open the best result in its own tab so I can review it. Then do the same search but for Pittsburgh to Palm Springs International Airport (PSP) instead, because flying directly into Palm Springs might save me the drive entirely, and open that result in its own tab too so I can compare the two side by side. Once you've got both flight options, pull up Google Maps and check the drive time from LAX to Palm Springs, because I only want to drive between 9am and 4pm — so if the LAX flight lands too late to make that window, either adjust the flight date or find me a hotel near LAX on Booking.com for an overnight stay before driving, and leave the hotel page open so I can see the price and location. If PSP ends up being the better option and skips the drive issue entirely, flag that clearly. After that, search for car rental options at whichever airport makes more sense for the dates I'd need, and open at least one rental listing so I can see the vehicle type and daily rate. Then check whether I could squeeze in a stop at either Soban or Holbox on any of the drives between the airport and Palm Springs — look up both on Google Maps, see how far each detour would add, and recommend which one is actually worth it given the 9am–4pm driving constraint. Finally, open CryptPad and create a new document where you lay out the full day-by-day itinerary covering the chosen flights, the drive or lack thereof, hotel if needed, car rental, the wedding on the 3rd, and the recommended detour stop, and leave the CryptPad doc open so I can edit it later.",
  },
  {
    level: "high",
    title: "A summer KBO stadium tour, fully bookable",
    text: "I’m daydreaming about doing a full summer KBO baseball trip through South Korea and I want to make it feel like a real, bookable plan instead of just a rough idea. Please start on koreabaseball.com and pull the current KBO schedule, then identify all 10 active KBO stadiums and choose one actual summer game at each stadium, ideally in a route that won’t make me zigzag all over the country. Once you have those 10 game dates and matchups, use Google Flights and Google Maps or Google Travel to figure out the cheapest practical way to move between each stop, whether that means flights, trains, buses, or driving, because I want the route to be efficient and budget-conscious. After that, go to Booking.com and find one solid place to stay near each stadium for the corresponding game night, aiming for convenient locations and reasonable prices rather than luxury. Then use Google Search to research what each city is especially known for eating, and use Yelp to turn that into a real food plan for every stop with specific restaurants, markets, or street-food areas I could actually visit around the game. As you do this, please open the actual hotel listings in their own tabs so I can compare photos and map locations, and for at least a couple of the food stops, open the real listing pages so I can visually verify they look active and worth visiting. When it all comes together, put everything into a CryptPad Document with the stadium, city, game date and matchup, travel leg, lodging, food plan, and estimated costs for each stop, and leave the finished doc open so I can review it.",
  },
];
