// In-memory fixtures for parser tests. A File polyfill keeps tests DOM-free.

export function fileOf(name: string, content: string): File {
  return new File([content], name, { type: "text/plain" });
}

export const SAMPLE_MBOX = [
  "From 1234@xxx Mon Jul 20 10:11:12 +0000 2026",
  "Message-ID: <msg-1@mail.example.com>",
  "Date: Mon, 20 Jul 2026 10:11:12 +0000",
  "From: Jane Doe <jane.doe@example.com>",
  "To: Lawrence Jang <lj@example.com>, Bob <bob@example.com>",
  "Subject: =?utf-8?B?VHJpcCBwbGFucyDinIg=?=",
  "X-Gmail-Labels: Inbox,Travel",
  "Content-Type: multipart/alternative; boundary=\"bnd1\"",
  "",
  "--bnd1",
  "Content-Type: text/plain; charset=utf-8",
  "Content-Transfer-Encoding: quoted-printable",
  "",
  "Hi Lawrence, flights are booked! Confirmation ABC123. Cost was $432.10.=",
  "",
  "See you, Jane",
  ">From my phone",
  "--bnd1",
  "Content-Type: text/html; charset=utf-8",
  "",
  "<p>Hi Lawrence</p>",
  "--bnd1--",
  "",
  "From 5678@xxx Tue Jul 21 09:00:00 +0000 2026",
  "Message-ID: <msg-2@amazon.com>",
  "Date: Tue, 21 Jul 2026 09:00:00 +0000",
  "From: Amazon.com <ship-confirm@amazon.com>",
  "To: Lawrence Jang <lj@example.com>",
  "Subject: Your Amazon.com order has shipped",
  "List-Unsubscribe: <mailto:unsub@amazon.com>",
  "Content-Type: text/plain; charset=utf-8",
  "",
  "Your order 123-4567890-1234567 has shipped.",
  "Order Total: $56.78",
  "",
  "From 7777@xxx Wed Jul 22 08:00:00 +0000 2026",
  "Message-ID: <msg-news@newsletter.example.org>",
  "Date: Wed, 22 Jul 2026 08:00:00 +0000",
  "From: Weekly Digest <noreply@newsletter.example.org>",
  "To: lj@example.com",
  "Subject: Your weekly digest",
  "List-Unsubscribe: <mailto:unsub@newsletter.example.org>",
  "Content-Type: text/plain; charset=utf-8",
  "",
  "This week's top stories...",
  "",
  "From 9999@xxx Wed Jul 22 09:00:00 +0000 2026",
  "Message-ID: <msg-3@old.example.com>",
  "Date: Wed, 22 Jul 2015 09:00:00 +0000",
  "From: Ancient Sender <old@old.example.com>",
  "To: lj@example.com",
  "Subject: Very old mail",
  "Content-Type: text/plain",
  "",
  "This one is from 2015 and should fall outside the date floor.",
  "",
].join("\r\n");

export const SAMPLE_EML = [
  "Message-ID: <eml-1@mail.example.com>",
  "Date: Thu, 23 Jul 2026 15:00:00 +0000",
  "From: attach@example.com",
  "To: lj@example.com",
  "Subject: With attachment",
  "Content-Type: multipart/mixed; boundary=\"bnd2\"",
  "",
  "--bnd2",
  "Content-Type: text/plain",
  "",
  "See attached invoice. My password: hunter2 by the way.",
  "--bnd2",
  "Content-Type: application/pdf; name=\"invoice.pdf\"",
  "Content-Disposition: attachment; filename=\"invoice.pdf\"",
  "Content-Transfer-Encoding: base64",
  "",
  "JVBERi0xLjQKJcTl8uXrp/Og0MTGCg==",
  "--bnd2--",
  "",
].join("\r\n");

export const SAMPLE_ICS = [
  "BEGIN:VCALENDAR",
  "VERSION:2.0",
  "BEGIN:VEVENT",
  "UID:evt-1@google.com",
  "DTSTART;TZID=America/New_York:20260715T140000",
  "DTEND;TZID=America/New_York:20260715T150000",
  "SUMMARY:Coffee with Jane\\, downtown",
  "LOCATION:Blue Bottle\\; 5th Ave",
  "DESCRIPTION:Catch up about the trip\\nBring the itinerary",
  "ORGANIZER;CN=Lawrence Jang:mailto:lj@example.com",
  "ATTENDEE;CN=Jane Doe:mailto:jane.doe@example.com",
  "STATUS:CONFIRMED",
  "END:VEVENT",
  "BEGIN:VEVENT",
  "UID:evt-2@google.com",
  "DTSTART;VALUE=DATE:20260801",
  "SUMMARY:Vacation day",
  "RRULE:FREQ=YEARLY",
  "END:VEVENT",
  "END:VCALENDAR",
].join("\r\n");

export const SAMPLE_VCF = [
  "BEGIN:VCARD",
  "VERSION:3.0",
  "FN:Jane Doe",
  "N:Doe;Jane;;;",
  "EMAIL;TYPE=HOME:jane.doe@example.com",
  "EMAIL;TYPE=WORK:jdoe@work.example.com",
  "TEL;TYPE=CELL:+1 (412) 555-0187",
  "ORG:Example Corp",
  "END:VCARD",
  "BEGIN:VCARD",
  "VERSION:2.1",
  "FN;ENCODING=QUOTED-PRINTABLE:Bob=20Smith",
  "TEL:412.555.0199",
  "END:VCARD",
].join("\r\n");

export const SAMPLE_WHATSAPP_IOS = [
  "[19/07/26, 21:15:03] Jane Doe: See you tomorrow at the airport?",
  "[19/07/26, 21:16:10] Lawrence: Yes! Gate B12",
  "still packing though",
  "[20/07/26, 08:00:00] Jane Doe: <Media omitted>",
  "[20/07/26, 08:01:00] Jane Doe: Messages and calls are end-to-end encrypted. No one outside of this chat can read them.",
].join("\n");
